"""
LangGraph State Definition
--------------------------
Defines the strongly typed state for the AI Assistant's LangGraph workflow.
"""

from typing import TypedDict, List, Dict, Any, Optional


class ConversationMessage(TypedDict):
    """Represents a message in the conversation history."""
    role: str  # 'user' or 'assistant'
    content: str


class AgentState(TypedDict):
    """
    Strongly typed state containing conversation context,
    intent classification, extracted fields, database query filters,
    and agent responses.
    """
    user_message: str
    conversation_history: List[ConversationMessage]
    detected_intent: Optional[str]  # 'log_interaction', 'edit_interaction', 'search_interaction', etc.
    extracted_data: Optional[Dict[str, Any]]  # Output of Log, Edit, or Search tools
    ai_response: Optional[str]  # Final response generated by the assistant
    database_result: Optional[Any]  # Placeholder for DB query outputs if needed
    errors: List[str]  # Any errors caught during workflow execution
