"""create_interactions_table

Revision ID: fb9015540047
Revises: 
Create Date: 2026-07-15 23:05:38.654351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9015540047'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'interactions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('hcp_name', sa.String(length=255), nullable=False),
        sa.Column('hospital_clinic_name', sa.String(length=255), nullable=True),
        sa.Column('hcp_specialty', sa.String(length=100), nullable=True),
        sa.Column('interaction_type', sa.String(length=50), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('time', sa.String(length=10), nullable=True),
        sa.Column('interaction_duration', sa.Float(), nullable=True),
        sa.Column('meeting_mode', sa.String(length=50), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('attendees', sa.Text(), nullable=True),
        sa.Column('topics_discussed', sa.Text(), nullable=True),
        sa.Column('materials_shared', sa.Text(), nullable=True),
        sa.Column('samples_distributed', sa.Text(), nullable=True),
        sa.Column('product_discussed', sa.String(length=255), nullable=True),
        sa.Column('hcp_sentiment', sa.String(length=50), nullable=True),
        sa.Column('priority', sa.String(length=20), nullable=True),
        sa.Column('outcomes', sa.Text(), nullable=True),
        sa.Column('follow_up_actions', sa.Text(), nullable=True),
        sa.Column('next_follow_up_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_hcp_name'), 'interactions', ['hcp_name'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_hcp_name'), table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
