"""
Chat API Schemas
----------------
Pydantic models representing request and response shapes for the AI assistant chat endpoint.
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional


class ChatMessageSchema(BaseModel):
    """Represents a message inside conversation history."""
    role: str = Field(..., description="'user' or 'assistant'")
    content: str = Field(..., description="Message text content")


class ChatRequest(BaseModel):
    """Request payload sent by the frontend assistant chat panel."""
    message: str = Field(..., min_length=1, description="The user's input text")
    history: List[ChatMessageSchema] = Field(
        default=[],
        description="Previous message exchanges for conversational context"
    )


class ChatResponse(BaseModel):
    """Response payload returned by the AI assistant."""
    reply: str = Field(..., description="Conversational text response generated by the agent")
    detected_intent: str = Field(..., description="Detected intent label (e.g. log_interaction)")
    extracted_data: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Structured JSON fields extracted by the AI tools (if any)"
    )
    errors: List[str] = Field(default=[], description="Any error messages encountered")
